{
    'name': 'Adi Track Products invoiced',
    'version': '15.0.0.0',
    'sequence': 1,
    'category': 'Sales',
    'summary': 'Adi Track Products invoiced . ',
    'description': "Adi Track Products invoiced ",
    "author" : "ADICOPS",
    "email": 'info@adicops.com',
    "website":'https://adicops.com/',
    'license': 'AGPL-3',
    'depends': ['base', 'account', 'product', 'stock'],
      "data":  [
       # 'security/ir.model.access.csv',
       # 'views/product.xml',
         'views/account_journal_views.xml',
        'views/product_template_views.xml',
        'views/account_journal_views.xml',
        ],
    'demo': [],
    'test': [],
    'qweb': [],    
    'images': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
