{
    'name': 'Adi Partner Credit Limit',
    'version': '15.0.0.0',
    'sequence': 1,
    'category': 'Sales',
    'summary': 'Adi Partner Limit  . ',
    'description': "ADI partner Limit. ",
    "author" : "ADICOPS",
    "email": 'info@adicops.com',
    "website":'https://adicops.com/',
    'license': 'AGPL-3',
    'depends': [
        'sale',        
        'account',        
    ], 
    "data":  [
       # 'security/ir.model.access.csv',
       # 'views/product.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        ],
    'demo': [],
    'test': [],
    'qweb': [],    
    'images': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
